spring.application.name=PlataformaSaludMental

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_db
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server
server.port=8080

# Verificacion Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=our_email@gmail.com
spring.mail.password=our_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Directorio para guardar los archivos CUD subidos
file.upload-dir=./uploads/cuds